defmodule TeamrcWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :teamrc

  @default_session_options [
    store: :cookie,
    key: "_teamrc_key",
    signing_salt: "46xYNHT2",
    encryption_salt: "k9Pm3xR7",
    same_site: "Lax"
  ]

  # Runtime session config (e.g. salts from runtime.exs) should override defaults.
  def session_options do
    endpoint_config = Application.get_env(:teamrc, __MODULE__, [])
    runtime_overrides = Keyword.get(endpoint_config, :session_options, [])
    Keyword.merge(@default_session_options, runtime_overrides)
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {__MODULE__, :session_options, []}]],
    longpoll: [connect_info: [session: {__MODULE__, :session_options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :teamrc,
    gzip: not code_reloading?,
    only: TeamrcWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 256_000,
    body_reader: {TeamrcWeb.Plugs.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :put_runtime_session
  plug TeamrcWeb.Router

  defp put_runtime_session(conn, _opts) do
    opts = session_options()
    Plug.Session.call(conn, Plug.Session.init(opts))
  end
end
